Added NextJS and AngularJS
aaryan2134/Engineering-Resources pull request #100
Opened 2022-10-21 16:21 UTC by Delvitron1019

![image](https://user-images.githubusercontent.com/96745112/197242925-f1f0f338-f21e-44d4-95bc-ac4263ab9c69.png)

2022-10-21 20:58 UTC, aaryan2134 requested changes

2022-10-21 20:58 UTC, aaryan2134 commented on README.md
> +1.  [documentation](https://www.w3schools.io/learn/nextjs-tutorial/).
Please make the first letter capital

2022-10-21 20:58 UTC, aaryan2134 commented on README.md
> +1.  [documentation](https://www.w3schools.io/learn/nextjs-tutorial/).
Also, please write in same format as "Angular.js Documentation"

2022-10-22 04:46 UTC, Delvitron1019 commented
I have made the changes as per your request.

![image](https://user-images.githubusercontent.com/96745112/197320225-91481fac-68c6-4f95-8b82-7da9c488d59f.png)

2022-10-22 19:25 UTC, aaryan2134 commented
Awesome!
Thank you for your contribution

2022-10-22 19:25 UTC, merged