Added 6 resources in various fields
aaryan2134/Engineering-Resources pull request #104
Opened 2022-10-22 19:54 UTC by LegendaryGene

Added 6 crucial resources in EE, ME, ML and CP fields

2022-10-23 19:14 UTC, LegendaryGene commented
Please Merge @aaryan2134

2022-10-25 12:00 UTC, aaryan2134 requested changes
Please make the necessary changes

2022-10-25 12:00 UTC, aaryan2134 commented on README.md
> +8. [MicroElectrnics Course](https://www.youtube.com/watch?v=366BVdmcUxk&list=PLLy_2iUCG87C-GS7B4vJ37Iz3fevmYU1h)
Please correct the spelling

2022-10-25 12:00 UTC, aaryan2134 commented on README.md
> +13. [CP Ladder CodeForces](https://www.google.com/url?sa=t&source=web&rct=j&url=https://earthshakira.github.io/a2oj-clientside/server/Ladders.html&ved=2ahUKEwiw6fOJxeb2AhXXAYgKHUhJCxQQFnoECAQQAQ&usg=
Please rectify this link

2022-10-25 12:00 UTC, aaryan2134 commented on README.md
> +14. [GeeksForGeeks](https://www.geeksforgeeks.org/)
This is not an appropriate resource for this section

2022-10-25 12:07 UTC, LegendaryGene commented on README.md
> +13. [CP Ladder CodeForces](https://www.google.com/url?sa=t&source=web&rct=j&url=https://earthshakira.github.io/a2oj-clientside/server/Ladders.html&ved=2ahUKEwiw6fOJxeb2AhXXAYgKHUhJCxQQFnoECAQQAQ&usg=
This link is working isn't it?

2022-10-25 12:21 UTC, LegendaryGene commented
Please review @aaryan2134

2022-10-25 12:22 UTC, aaryan2134 commented
Please resolve conflicts

2022-10-25 12:23 UTC, aaryan2134 commented
Otherwise it looks good

2022-10-25 12:27 UTC, LegendaryGene commented
Shall I open a new PR @aaryan2134, don't really know how to resolve the issue

2022-10-25 12:41 UTC, LegendaryGene commented
> Please resolve conflicts

Done @aaryan2134 , please merge asap, thanks :P

2022-10-26 17:49 UTC, aaryan2134 commented
Thank you

2022-10-26 17:49 UTC, merged